// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProxy = `-- name: CreateProxy :one
INSERT INTO proxies (address, username, password) 
VALUES ($1, $2, $3) 
ON CONFLICT (address) DO NOTHING 
RETURNING id, address, username, password, is_active, last_used_at, created_at
`

type CreateProxyParams struct {
	Address  string
	Username pgtype.Text
	Password pgtype.Text
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, createProxy, arg.Address, arg.Username, arg.Password)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Username,
		&i.Password,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingTask = `-- name: GetPendingTask :one
SELECT 
    t.id, t.status, t.attempts, t.max_attempts, t.proxy_id, t.payload, t.error_message, t.created_at, t.updated_at, 
    p.address AS proxy_address, 
    p.username AS proxy_username, 
    p.password AS proxy_password
FROM tasks t
LEFT JOIN proxies p ON t.proxy_id = p.id
WHERE t.status = 'pending' 
ORDER BY t.created_at ASC 
LIMIT 1
FOR UPDATE OF t SKIP LOCKED
`

type GetPendingTaskRow struct {
	ID            pgtype.UUID
	Status        NullTaskStatus
	Attempts      pgtype.Int4
	MaxAttempts   pgtype.Int4
	ProxyID       pgtype.Int4
	Payload       []byte
	ErrorMessage  pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ProxyAddress  pgtype.Text
	ProxyUsername pgtype.Text
	ProxyPassword pgtype.Text
}

func (q *Queries) GetPendingTask(ctx context.Context) (GetPendingTaskRow, error) {
	row := q.db.QueryRow(ctx, getPendingTask)
	var i GetPendingTaskRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ProxyID,
		&i.Payload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProxyAddress,
		&i.ProxyUsername,
		&i.ProxyPassword,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $1, updated_at = NOW(), error_message = $2 WHERE id = $3 RETURNING id, status, attempts, max_attempts, proxy_id, payload, error_message, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	Status       NullTaskStatus
	ErrorMessage pgtype.Text
	ID           pgtype.UUID
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.Status, arg.ErrorMessage, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ProxyID,
		&i.Payload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
